config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # user
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'user/registrations#new', as: :new_user_registration
    post 'signup' => 'user/registrations#create', as: :user_registration
    get 'signup/cancel' => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'user' => 'devise/registrations#edit', as: :edit_user_registration
    patch 'user' => 'devise/registrations#update', as: nil
    put 'user' => 'devise/registrations#update', as: :update_user_registration
    delete 'user' => 'devise/registrations#destroy', as: :destroy_user_registration
    get 'password' => 'devise/passwords#new', as: :new_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    patch 'password' => 'devise/passwords#update'
    put 'password' => 'devise/passwords#update', as: :update_user_password
  end

  # admin
  namespace :admin do
    get '/', to: 'user#index'
    resources :user
  end

  # Task
  get '/', to: 'task#index'
  resources :task do
    collection do
      get "search"
    end
  end
  
  get '*path', controller: 'application', action: 'render_404'
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    has_many :task_labels, dependent: :destroy
    
    enum :status, {ready: 0, running: 1, finished: 2}
    validates :title, presence: true, length: { maximum: 256 }

    def self.ransackable_attributes(auth_object = nil)
        ["status", "title", "user_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["task_labels", "user"]
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!
  before_action :set_labels, only: %i[ index show new edit create update ]
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_q, only: %i[ index ]

  def index
    @results = @q.result(distinct: true).includes(:task_labels).order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @p = task_params

    # FIX ME: 
    # 空白が含まれているかつ文字列配列になっているので、空白は取り除いて、文字⇒数値に変換している
    # 出来ればparamsの段階で既に TaskLabelsモデルの配列になっているほうが良い
    task_labels = []
    @p[:task_labels].compact_blank.map{|n| n.to_i}.each do |id|
      task_labels.push(TaskLabel.new(label_id: id))
    end
    @p[:task_labels] = task_labels
    @task = Task.new(@p)

    # TODO: ユーザーIDはセッションから取得する
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_index_url, notice: ta_t("notice.new") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_index_url, notice: ta_t("notice.edit") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to task_index_url, notice: ta_t("notice.destroy") }
    end
  end

  private 

    def set_labels
      @labels = Label.where(user_id: current_user.id)
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def set_q
      # ログインユーザーのユーザーIDを検索条件に含む
      if params[:q] == nil
        params[:q] = {:user_id_eq => current_user.id}
      else
        params[:q][:user_id_eq] = current_user.id
      end
      @q = Task.ransack(params[:q])
    end

    def task_params
      params.require(:task).permit(:title, :description, :ended_at, :status, {task_labels: []})
    end
    
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/task/edit.html.erb
<%= form_for @task, url: task_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :title, ta_t("form.title"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_field :title, reqired: true, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :description, ta_t("form.description"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_area  :description, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :ended_at, ta_t("form.ended_at"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.date_field :ended_at, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :status, ta_t("form.status"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {}, class: "form-select" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-sm-12 col-md-12 text-center">
        <%= link_to ta_t("form.back"), task_index_path, method: :get, class: "btn m-1 btn-secondary py-2 px-5" %>
        <%= f.submit ta_t("form.submit"), class: "btn btn-primary py-2 px-5" %>
      </div>
    </div>
  </div>
  <% if @task.errors.any? %>
    <div style="color: red">
      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/task/index.html.erb
<div class="row mb-2">
  <%= button_to ta_t("btn.new"), new_task_path, method: :get, class: "btn my-2 btn-primary" %>
  <%= search_form_for @q, url: task_index_path do |f| %>
    <%= f.search_field :title_cont, placeholder: ta_t("search.form.title") %>
    <%= f.select :status_eq, Task.statuses_i18n.invert.map {|k, v| [k, Task.statuses[v]]} %>
    <%= f.submit ta_t("search.form.submit") %>
  <% end %>
</div>
<div class="row mb-2">
  <table class="table table-bordere table-striped table-hover table-responsive align-middle">
    <thead class="table-light">
      <tr class="text-center">
        <th scope="col" class="w-no"><%= sort_link(@q, :id, "#")%></th>
        <th scope="col" class="w-date"><%= sort_link(@q, :created_at, ta_t("results.header.created_at"))%></th>
        <th scope="col"><%= sort_link(@q, :title, ta_t("results.header.title")) %></th>
        <th scope="col"><%= sort_link(@q, :status, ta_t("results.header.label")) %></th>
        <th scope="col" class="w-status"><%= sort_link(@q, :status, ta_t("results.header.status")) %></th>
        <th scope="col" class="w-date"><%= sort_link(@q, :ended_at, ta_t("results.header.ended_at")) %></th>
        <th scope="col" class="w-button"><%= ta_t("results.header.action") %></th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |r| %>
      <tr>
        <td class="text-center"><%= r.id %></td>
        <td><%= l(r.created_at) %></td>
        <td><%= link_to r.title, task_path(r.id) %></td>
        <td>
          <% r.task_labels.each do |tl| %>
            <span class="badge bg-secondary"><%= tl.label.name %></span>
          <% end %>
        </td>
        <td class="text-center"><%= I18n.t("enums.task.status.#{r.status}") %></td>
        <td class="text-center"><%= l(r.ended_at, default: "-") %></td>
        <td class="text-center">
        <div class="d-flex justify-content-center">
          <%= button_to ta_t("results.body.btn.edit"), edit_task_path(r.id), method: :get, class: "btn btn-sm mx-1 btn-outline-success" %>
          <%= button_to ta_t("results.body.btn.destroy"), task_path(r.id), method: :delete, class: "btn btn-sm mx-1 btn-outline-danger" %>
        </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @results, theme: 'bootstrap-5' %>
<%= render partial: 'layouts/flash' %>

app/views/task/new.html.erb
<%= form_for @task, url: task_index_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :title, ta_t("form.title"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_field :title, reqired: true, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :description, ta_t("form.description"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_area  :description, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :ended_at, ta_t("form.ended_at"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.date_field :ended_at, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :status, ta_t("form.status"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {}, class: "form-select" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :task_labels, ta_t("form.label"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.select :task_labels, @labels.all.map{|l| [l.name, l.id]}, {}, class: "form-select",:multiple => true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-sm-12 col-md-12 text-center">
        <%= link_to ta_t("form.back"), task_index_path, method: :get, class: "btn m-1 btn-secondary py-2 px-5" %>
        <%= f.submit ta_t("form.submit"), class: "btn btn-primary py-2 px-5" %>
      </div>
    </div>
  </div>
  <% if @task.errors.any? %>
    <div style="color: red">
      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/task/show.html.erb
<%= form_for @task, url: task_index_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :title, ta_t("form.title"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :title, reqired: true, class: "form-control", readonly: true %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :description, ta_t("form.description"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_area  :description, class: "form-control", readonly: true %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :ended_at, ta_t("form.ended_at"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.date_field :ended_at, class: "form-control", readonly: true %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :status, ta_t("form.status"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]}, {}, class: "form-select", disabled: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-sm-12 col-md-12 text-center">
        <%= link_to ta_t("btn.back"), task_index_path, method: :get, class: "btn m-1 btn-secondary py-2 px-5" %>
        <%= link_to ta_t("btn.edit"), edit_task_path(@task.id), method: :get, class: "btn m-1 btn-primary py-2 px-5" %>
      </div>
    </div>
  </div>
  <% if @task.errors.any? %>
    <div style="color: red">
      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>