config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # user
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup' => 'user/registrations#new', as: :new_user_registration
    post 'signup' => 'user/registrations#create', as: :user_registration
    get 'signup/cancel' => 'devise/registrations#cancel', as: :cancel_user_registration
    get 'user' => 'devise/registrations#edit', as: :edit_user_registration
    patch 'user' => 'devise/registrations#update', as: nil
    put 'user' => 'devise/registrations#update', as: :update_user_registration
    delete 'user' => 'devise/registrations#destroy', as: :destroy_user_registration
    get 'password' => 'devise/passwords#new', as: :new_user_password
    post 'password' => 'devise/passwords#create', as: :user_password
    get 'password/edit' => 'devise/passwords#edit', as: :edit_user_password
    patch 'password' => 'devise/passwords#update'
    put 'password' => 'devise/passwords#update', as: :update_user_password
  end

  # admin
  namespace :admin do
    get '/', to: 'user#index'
    resources :user
  end

  # Task
  get '/', to: 'task#index'
  resources :task do
    collection do
      get "search"
    end
  end
  
  get '*path', controller: 'application', action: 'render_404'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :labels, dependent: :destroy
  has_many :tasks, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.ransackable_attributes(auth_object = nil)
    ["email", "name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["tasks"]
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :admin_authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_q, only: %i[ index ]

  def index
    @results = @q.result(distinct: true).includes(:tasks).order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_create)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_index_url, notice: ta_t("notice.new") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params_update)
        format.html { redirect_to admin_user_index_url, notice: ta_t("notice.edit") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    # 管理者ユーザーは2人以上必要
    if User.where.not(id: [current_user.id, @user.id]).where(is_admin: true).size < 1
      respond_to do |format|
        format.html { redirect_to admin_user_index_url, alert: ta_t("alert.destroy") }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_user_index_url, notice: ta_t("notice.destroy") }
      end
    end
  end

  private 
    def set_user
      @user = User.find(params[:id])
    end

    def set_q
      @q = User.ransack(params[:q])
    end

    def user_params_create
      params.require(:user).permit(:name, :email, :password, :password_confirm, :is_admin)
    end

    def user_params_update
      params.require(:user).permit(:name, :email)
    end

    def admin_authenticate_user!
      authenticate_user!
      unless current_user.is_admin
        routing_error
        # redirect_to task_index_url
      end
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    print 'test'
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_session_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/views/admin/user/edit.html.erb
<%= form_for @user, url: admin_user_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :name, ta_t("form.name"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_field :name, reqired: true, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :email, ta_t("form.email"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.email_field :email, reqired: true, autocomplete: "email", class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3 text-center">
      <div class="col-sm-12 col-md-12">
        <%= f.submit ta_t("form.submit"), class: "btn btn-primary py-2 px-5" %>
      </div>
    </div>
  <% if @user.errors.any? %>
    <div style="color: red">
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/admin/user/index.html.erb
<div class="row mb-2">
  <%= button_to ta_t("btn.new"), new_admin_user_path, method: :get, class: "btn my-2 btn-primary" %>
  <%= search_form_for @q, url: admin_user_index_path do |f| %>
    <%= f.search_field :name_cont, placeholder: ta_t("search.form.name") %>
    <%= f.search_field :email_cont, placeholder: ta_t("search.form.email") %>
    <%= f.submit ta_t("search.form.submit") %>
  <% end %>
</div>
<div class="row mb-2">
  <table class="table table-bordere table-striped table-hover table-responsive align-middle">
    <thead class="table-light">
      <tr class="text-center">
        <th scope="col" class="w-no"><%= sort_link(@q, :id, "#")%></th>
        <th scope="col"><%= sort_link(@q, :name, ta_t("results.header.name"))%></th>
        <th scope="col"><%= sort_link(@q, :email, ta_t("results.header.email")) %></th>
        <th scope="col"><%= sort_link(@q, :email, ta_t("results.header.task_count")) %></th>
        <th scope="col"><%= sort_link(@q, :email, ta_t("results.header.is_admin")) %></th>
        <th scope="col" class="w-date"><%= sort_link(@q, :created_at, ta_t("results.header.created_at")) %></th>
        <th scope="col" class="w-button"><%= ta_t("results.header.action") %></th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |r| %>
      <tr>
        <td class="text-center"><%= r.id %></td>
        <td><%= link_to r.name, admin_user_path(r.id) %></td>
        <td><%= r.email %></td>
        <td class="text-end"><%= r.tasks.size %></td>
        <td class="text-center">
          <% if r.is_admin %>
            <%= ta_t("results.body.is_admin.y") %>
          <% else %>
            <%= ta_t("results.body.is_admin.n") %>
          <% end %>
        </td>
        <td class="text-center"><%= l(r.created_at) %></td>
        <td class="text-center">
        <div class="d-flex justify-content-center">
          <%= button_to ta_t("results.body.btn.edit"), edit_admin_user_path(r.id), method: :get, class: "btn btn-sm mx-1 btn-outline-success" %>
          <% if r.id != current_user.id %>
            <%= button_to ta_t("results.body.btn.destroy"), admin_user_path(r.id), method: :delete, class: "btn btn-sm mx-1 btn-outline-danger" %>
          <% end %>
        </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @results, theme: 'bootstrap-5' %>
<%= render partial: 'layouts/flash' %>

app/views/admin/user/new.html.erb
<%= form_for @user, url: admin_user_index_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :name, ta_t("form.name"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_field :name, reqired: true, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :email, ta_t("form.email"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.email_field :email, reqired: true, autocomplete: "email", class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :password, ta_t("form.password"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.password_field :password, reqired: true, autocomplete: "new-password", class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :password_confirmation, ta_t("form.password_confirmation"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.password_field :password_confirmation, reqired: true, autocomplete: "new-password", class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :is_admin, ta_t("form.is_admin"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10 d-flex align-items-center">
        <div class="form-check form-switch">
          <%= f.check_box :is_admin, class: "form-check-input" %>
        </div>
      </div>
    </div>

    <div class="row mb-3 text-center">
      <div class="col-sm-12 col-md-12">
        <%= f.submit ta_t("form.submit"), class: "btn btn-primary py-2 px-5" %>
      </div>
    </div>
  <% if @user.errors.any? %>
    <div style="color: red">
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/admin/user/show.html.erb
<%= form_for @user, url: admin_user_index_path, html: {class: "card col-6 mt-5 mx-auto"} do |f| %>
  <div class="card-header">
    <h2 class="text-center" ><%= ta_t("title") %></h2>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <%= f.label :name, ta_t("form.name"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.text_field :name, reqired: true, autofocus: true, class: "form-control", readonly: true %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :email, ta_t("form.email"), class: "col-sm-12 col-md-2 col-form-label" %>
      <div class="col-sm-12 col-md-10">
        <%= f.email_field :email, reqired: true, autocomplete: "email", class: "form-control", readonly: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-sm-12 col-md-12 text-center">
        <%= link_to ta_t("btn.back"), admin_user_index_path, method: :get, class: "btn m-1 btn-secondary py-2 px-5" %>
        <%= link_to ta_t("btn.edit"), edit_admin_user_path(@user.id), method: :get, class: "btn m-1 btn-primary py-2 px-5" %>
      </div>
    </div>
  </div>
  <% if @user.errors.any? %>
    <div style="color: red">
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>